FROM almalinux:9
ENV course="devops" \
    duration="120hrs"
ARG trainer="sk"
ENV trainer=${trainer}
RUN echo "Namasthe Macha! ${course} is semma exciting and duration is ${duration} by ${trainer}"
CMD ["sleep", "1000"]
